version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      wrangler:
        patterns:
          - wrangler
          - "@cloudflare/*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
